version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "02:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated-update"
    reviewers:
      - "porfanid"
    assignees:
      - "porfanid"
    milestone: 1
    rebase-strategy: "auto"
    pull-request-branch-name:
      separator: "_"