name: Test Lexer

on: [push, pull_request]

jobs:
  test_lexer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run test_lexer
      run: |
        source .venv/bin/activate
        python -m unittest tests/test_lexer.py

  test_parser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run another test
      run: |
        source .venv/bin/activate
        python -m unittest tests/test_parser.py

  upload_combined:
    runs-on: ubuntu-latest
    needs: [test_lexer, test_parser]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run final task
      run: |
        source .venv/bin/activate
        python scripts/combine.py

    - name: Upload combined_compiler.py
      uses: actions/upload-artifact@v4
      with:
        name: combined_compiler
        path: ./scripts/combined_compiler.py